paths:
  dataset_path: '/content/drive/MyDrive/Master_Thesis/train_data/WikiTokenized'
  save_path: '/content/sample_data'
q_model:
  path: "sentence-transformers/all-distilroberta-v1"
  special_tokens: []
d_model:
  path: "sentence-transformers/all-distilroberta-v1"
  special_tokens: []
training:
  batch_size: 8
  num_pos: 3
  epochs: 5
  lr: 1.0E-5
  mode: "bi-encoder"
  eval_freq: 0.001
  accumulation_steps: 5
logging:
  print_freq: 5
cross_batch_memory:
  use: True
  buffer_size: 160
  warmup: 1000
wandb:
  use: True
  credential_path: 'default'
  project_name: 'retrieval_training'