q_model_name: "sentence-transformers/all-distilroberta-v1"
d_model_name: "sentence-transformers/all-distilroberta-v1"
dataset_path: 'C:\Users\Daniel\Documents\RAG_thesis\data\sample_dataset'
save_path: 'C:\Users\Daniel\Documents\RAG_thesis\results'
batch_size: 10
epochs: 5
lr: 1.0E-5
mode: "bi-encoder"
print_freq: 5
eval_freq: "epoch"
cross_batch_memory:
  use: True
  buffer_size: 400
  warmup: 1000
accumulation_steps: 5