paths:
  dataset_path: '/content/drive/MyDrive/Master_Thesis/train_data/WikiTokenized'
  save_path: '/content/sample_data'
q_model:
  path: "sentence-transformers/all-distilroberta-v1"
  special_tokens: []
  model_args: {"num_poly_codes": 100}
d_model:
  path: ''
  special_tokens: ["Section::::", "BULLET::::"]
  model_args: {}
training:
  batch_size: 8
  num_pos: 3
  epochs: 5
  lr: 1.0E-5
  mode: "poly-encoder"
  use_torch_compile: False
  accumulation_steps: 5
evaluation:
  eval_freq: 10
  eval_accumulation: 50
  batch_size: 50
  faiss_device: "cpu"
logging:
  print_freq: 50
cross_batch_memory:
  use: True
  buffer_size: 160
  warmup: 1000
wandb:
  use: True
  credential_path: 'default'
  project_name: 'retrieval_training'